# Generated by Django 4.2.14 on 2024-08-01 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="merchant_logo",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
