# Generated by Django 4.2.14 on 2024-08-02 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bank_transaction", "0002_alter_merchant_merchant_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(choices=[("expense", "expense"), ("income", "income")], max_length=100),
        ),
        migrations.AlterField(
            model_name="keyword",
            name="merchant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bank_transaction.merchant"),
        ),
        migrations.AlterField(
            model_name="merchant",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="bank_transaction.category"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="bank_transaction.category"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="merchant",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="bank_transaction.merchant"
            ),
        ),
    ]
